### ISSUE TITLE
Issue attempting to save single-sheet file

### ISSUE THREAD

**Issue by bdfraser** [pyexcel/pyexcel-ods#11]
Just installed pyexcel-ods 0.1.1 via pip (which auto-installed the dependancies pyexcel-io 0.1.0 and odfpy 0.9.6)

Attempted to run the sample code from the site - specifically I attempted to use both the 'read from a file' and 'write to a file' code in one script, altering the data in between. My script was as follows:
```

    from pyexcel_ods import save_data, get_data

    gnsFile = "C:\\users\\main1\\documents\\gns 16-05-16.ods"

    data = get_data(gnsFile)
    data[0].append('Test')
    save_data(gnsFile, data)
```

However that resulted in the following error:
```

Traceback (most recent call last):
  File "GNSDataRetriever.py", line 11, in <module>
    save_data(gnsFile, data)
  File "C:\Python27\lib\site-packages\pyexcel_ods\__init__.py", line 335, in sav
e_data
    write_data(afile, data, file_type=file_type, **keywords)
  File "C:\Python27\lib\site-packages\pyexcel_io\__init__.py", line 260, in stor
e_data
    writer.write(data)
  File "C:\Python27\lib\site-packages\pyexcel_io\base.py", line 286, in write
    keys = sheet_dicts.keys()
AttributeError: 'list' object has no attribute 'keys'

```

I was able to work around it by changing the body of the write method in pyexcel_io/base.py to the following:

```
        try:
            keys = sheet_dicts.keys()
            for name in keys:
                sheet = self.create_sheet(name)
                if sheet is not None:
                    sheet.write_array(sheet_dicts[name])
                    sheet.close()
        except AttributeError:
            sheet = self.create_sheet('Sheet1')
            if sheet is not None:
                sheet.write_array(sheet_dicts)
                sheet.close()

```

(Of course it would be more correct to try to actually find out the actual sheet name and write it out as that rather than just Sheet1 - but for my use case it doesn't matter).

I haven't done any further testing (and am not likely to have to time to anytime soon, sadly), but it looks like the data object passed ends up being only a dict if there are multiple sheets, with each value in the dict being a list, but if there is only one sheet the list is all that gets passed, rather than a dict with one key and value. If I do get the time I'll test out that theory with a simple multi-sheet file.

I can provide a copy of the specific file that I noticed this issue with, if required - it doesn't contain anything particularly sensitive.

The version of libreoffice used to originally create the file was:

Version: 5.0.4.2
Build ID: 2b9802c1994aa0b7dc6079e128979269cf95bc78
Locale: en-AU (en_AU)

on windows.

Python version is:

Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32

**Comment by bdfraser** [comment]
I'm assuming we can just directly interact with the data object, there aren't any special functions we're supposed to use to write to it that me not using might have caused it to get messed up?

**Comment by chfw** [comment]
> I haven't done any further testing (and am not likely to have to time to anytime soon, sadly), but it looks like the data object passed ends up being only a dict if there are multiple sheets, with each value in the dict being a list, but if there is only one sheet the list is all that gets passed, rather than a dict with one key and value. 

Yes, that's true for pyexcel-io <= 0.1.0. And this behavior is correct only in un-released 0.2.0, where a consistent interface is given: a dictionary of two dimensional arrays is returned.

I have not updated this library to work with pyexcel-io 0.2.0 yet. but un-released pyexcel-ods3 v0.2.0 works  with pyexcel-io 0.2.0.

**Comment by chfw** [comment]
This library has been upgraded. Please wait for pyexcel-io 0.2.0. And will update this thread once it has been released.

**Comment by chfw** [comment]
Please try again with latest pyexcel-io 0.2.0+ and pyexcel-ods 0.2.0+. The interface should now be consistent.
