### ISSUE TITLE
isstream(instance) returns False if StringIO is from cStringIO package

### ISSUE THREAD

**Issue by hieu-n** [pyexcel/pyexcel-ods#12]
I am using pyexcel_ods.get_data with Flask to parse ODS files uploaded by users as below:

```
from cStringIO import StringIO
...
io = StringIO()
file_storage = request.files['filename.ods'] 
file_storage.save(io)
data = get_data(io)
```

(I am not sure this is the correct way to do it. If someone knows a better way, please point me out.)
That will rise:

```
  File "/env/lib/python2.7/site-packages/pyexcel_ods/__init__.py", line 344, in get_data
    return read_data(afile, file_type=file_type, **keywords)
  File "/env/lib/python2.7/site-packages/pyexcel_io/__init__.py", line 311, in get_data
    data = load_data(afile, file_type=file_type, **keywords)
  File "/env/lib/python2.7/site-packages/pyexcel_io/__init__.py", line 137, in load_data
    raise IOError(MESSAGE_ERROR_03)
IOError: cannot handle unknown content
```

If I change the first line to:
`from StringIO import StringIO`
It will work. But from the doc, cStringIO.StringIO is faster than StringIO.StringIO.

**Comment by chfw** [comment]
It is true that cStringIO was not supported. Will tackle it in next pyexcel-io release.

As to faster and better way to do what you were doing is to use Flask-Excel's built-in method [get_array](http://flask-excel.readthedocs.io/en/latest/#flask_excel.ExcelRequest.get_array):

    data = request.get_array('filename.ods') # shorter code, while the same actions are performed though

**Comment by chfw** [comment]
pyexcel-ezodf replaces ezodf  and had the cstringio suppport. Let's get this out of the door. This is a such a long journey: 25/Aug/2017

**Comment by chfw** [comment]
cStringIO should be now supported
