### ISSUE TITLE
Empty newlines missing from output

### ISSUE THREAD

**Issue by doakey3** [pyexcel/pyexcel-ods#17]
Say I have a spreadsheet with only 1 cell with this data:

```
Line 1

Line 2
```

There's a space in the middle, but this happens
```
>>> from pyexcel_ods import get_data
>>> print(get_data('example.ods')['Sheet1'])
[['Line 1\nLine2']]
```

I think there should be '\n\n' in there, not '\n'. Thanks

**Comment by chfw** [comment]
released to pypi
