### ISSUE TITLE
Support for "Open Document (Flat XML) .fodt"

### ISSUE THREAD

**Issue by joaompinto** [pyexcel/pyexcel-ods#18]
I am using .fodt for version control,  pyexcel-ods should be able to open .fodt files (it jut needs to skip the zip/unzip).

**Comment by chfw** [comment]
pyexcel-odsr already support fods and I am yet to add fods read support to pyexcel-ods3. However, since this library depends on odfpy. If they are not going to have it, I could do nothing about it.

**Comment by skierpage** [comment]
> However, since this library depends on odfpy. If they are not going to have it, I could do nothing about it.

FYI the related issue seems to be eea/odfpy#18 , open for 5 years.
