### ISSUE TITLE
Support modifying cells

### ISSUE THREAD

**Issue by chrisspen** [pyexcel/pyexcel-ods#21]
The docs imply that this package can only read an ODS file into a Python dictionary or write a Python dictionary to an ODS file. This destroys all data in the ODS file that doesn't have a Python equivalent, such as formatting and formulas. It would be convenient to be able to modify an ODS file in place, such as modifying only certain cells in the file.

**Comment by chfw** [comment]
Thanks for your interest in pyexcle-ods. I am afraid I am going to reject your issue. The reason are:

1. The goal of pyexcel is mainly to extract data from and store data back into excel formats, including ODS.
2. pyexcel-ods reply on odfpy for reading ODS. Hence, you would be advised to try with odfpy.

I have reserved the consideration to support some styles but have no plan to read the styles, formats and put the same back into the same file.
