### ISSUE TITLE
Exception shown in simple sheet - currency issue?

### ISSUE THREAD

**Issue by bitwombat** [pyexcel/pyexcel-ods#27]
The attached causes pyexcel_ods/odsr.py 0.5.2 to throw a TypeError on a simple read:

    data = get_data("test.ods")

[test.ods.gz](https://github.com/pyexcel/pyexcel-ods/files/1671741/test.ods.gz)

**Comment by chfw** [comment]
Thanks. I will have a look.

**Comment by chfw** [comment]
released in 0.5.3
