### ISSUE TITLE
Sheet.save_as ("output.ods") doesn't support long() values

### ISSUE THREAD

**Issue by AlainBarthe** [pyexcel/pyexcel-ods#30]
Got exception : AttributeError: 'long' object has no attribute 'split'

When running the code :

import pyexcel
sheet = pyexcel.Sheet()
sheet [0,0] = 123456678912345678901234567
sheet.save_as ("output.ods")

Seems to be due to pyexcel_io.service.ODS_WRITE_FORMAT_CONVERSION dictionnary, 
that is not aware of long() datatype

File : pyexecl_ods/odsw.py

cell_odf_type = converter.ODS_WRITE_FORMAT_CONVERSION.get(cell_type, "string")
...
if cell_odf_type != 'string':
   ...
else:
            lines = cell.split('\n')

Whereas long() values doesn't support split() -> exception

I would suggest to add long in ODS_WRITE_FORMAT_CONVERSION
Or cell.spit("\n") in a try...catch block

**Comment by chfw** [comment]
So, I would prefer that ods plugin to be number immutable.
